# Generated by Django 2.1 on 2018-08-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperminis', '0003_creaturequantity_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='color',
            field=models.CharField(choices=[('228b22', 'Green'), ('aa3939', 'Red'), ('005b96', 'Blue'), ('d3d3d3', 'Light Gray'), ('a9a9a9', 'Dark Gray'), ('000000', 'Black')], default='a9a9a9', max_length=6),
        ),
    ]
