# Generated by Django 2.1 on 2018-08-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperminis', '0005_printsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printsettings',
            name='base_shape',
            field=models.CharField(choices=[('square', 'Square'), ('hexagon', 'Hexagon'), ('circle', 'Circle')], default='square', max_length=50),
        ),
    ]
