# Generated by Django 2.1 on 2018-08-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperminis', '0006_auto_20180807_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='show_name',
            field=models.BooleanField(default=True),
        ),
    ]
