# Generated by Django 2.1 on 2018-08-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperminis', '0007_creature_show_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='position',
            field=models.CharField(choices=[('top', 'Flying (Top)'), ('center', 'Hovering (Middle)'), ('bottom', 'Walking (Bottom)')], default='bottom', max_length=50),
        ),
    ]
