# Generated by Django 2.1 on 2018-08-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperminis', '0009_creature_creature_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='CR',
            field=models.FloatField(default=0),
        ),
    ]
