# Generated by Django 2.1 on 2018-08-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperminis', '0010_creature_cr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
