# Generated by Django 2.1 on 2018-08-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperminis', '0013_auto_20180817_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestiary',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
