# Generated by Django 2.1 on 2018-08-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperminis', '0014_auto_20180830_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='printsettings',
            name='darken',
            field=models.IntegerField(default=0),
        ),
    ]
