# Generated by Django 2.2.9 on 2020-11-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperminis', '0016_printsettings_force_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestiary',
            name='from_ddb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creature',
            name='from_ddb',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='creature',
            name='color',
            field=models.CharField(choices=[('228b22', 'Green'), ('aa3939', 'Red'), ('005b96', 'Blue'), ('d3d3d3', 'Light Gray'), ('a9a9a9', 'Dark Gray'), ('000000', 'Black'), ('ffffff', 'White')], default='a9a9a9', max_length=6),
        ),
    ]
