# Generated by Django 3.2.13 on 2022-05-03 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paperminis', '0019_auto_20210831_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creature',
            name='CR',
        ),
        migrations.RemoveField(
            model_name='creature',
            name='creature_type',
        ),
    ]
