# Generated by Django 3.2.15 on 2022-09-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperminis', '0021_creature_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='cavalry_mode',
            field=models.BooleanField(default=False),
        ),
    ]
